create table EVENTS(
    ID        bigint         generated by default as identity,
    REP_DATE  date,
    AMOUNT    numeric(18, 2),
    STATUS    integer        default 0,
    REFERENCE uuid,
    MESSAGE   jsonb          check (MESSAGE ? 'client_id' and
                                    MESSAGE ? 'account_number' and
                                    MESSAGE ? 'operation_type'),
    constraint PK_EVENTS primary key (ID, REP_DATE)
) partition by range (REP_DATE);

create unique index IDX_EVENTS_REFERENCE on EVENTS(REFERENCE, REP_DATE);

create table EVENTS_DEFAULT partition of EVENTS default;
create table EVENTS_2026_01 partition of EVENTS for values from ('2026-01-01') to ('2026-02-01');
create table EVENTS_2026_02 partition of EVENTS for values from ('2026-02-01') to ('2026-03-01');
create table EVENTS_2026_03 partition of EVENTS for values from ('2026-03-01') to ('2026-04-01');
